"""
Shared product catalogs for command aliases and dashboard module control.
"""

from __future__ import annotations


ALIAS_COMMANDS = [
    "ping",
    "avatar",
    "banner",
    "uptime",
    "help",
    "server",
    "servericon",
    "serverbanner",
    "membercount",
    "userinfo",
    "roleinfo",
    "emojiinfo",
    "snipe",
    "remind",
    "reminders",
    "remindcancel",
    "afk",
    "kick",
    "ban",
    "unban",
    "mute",
    "unmute",
    "setupmute",
    "timeout",
    "untimeout",
    "warn",
    "warnings",
    "clearwarns",
    "delwarn",
    "clear",
    "slowmode",
    "note",
    "warnthreshold set",
    "warnthreshold list",
    "warnthreshold remove",
    "lockserver",
    "unlockserver",
    "automod toggle",
    "automod spam",
    "automod links",
    "automod words",
    "automod caps",
    "automod mentions",
    "automod exempt",
    "automod status",
    "autorole add",
    "autorole remove",
    "autorole list",
    "cc",
    "alias add",
    "alias remove",
    "alias list",
    "poll",
    "endpoll",
    "starboard",
    "disablestarboard",
    "temproom setup",
    "temproom rename",
    "temproom limit",
    "temproom lock",
    "temproom unlock",
    "temproom kick",
    "temproom ban",
    "temproom unban",
    "temproom transfer",
    "temproom delete",
    "temproom info",
    "invite",
    "play",
    "pause",
    "resume",
    "skip",
    "stop",
    "queue",
    "nowplaying",
    "volume",
    "loop",
    "shuffle",
    "remove",
    "join",
    "leave",
    "lyrics",
    "blacklist",
    "unblacklist",
    "blacklistview",
    "reload",
    "shutdown",
    "announce",
    "botstats",
    "dm",
]

MODULE_METADATA = {
    "cogs.general.ping": {"name": "Ping", "description": "Latency and health check command."},
    "cogs.general.avatar": {"name": "Avatar", "description": "Profile image and banner commands."},
    "cogs.general.uptime": {"name": "Uptime", "description": "Process uptime and runtime insight."},
    "cogs.general.serverinfo": {"name": "Server Info", "description": "Server, icon, banner, and member info."},
    "cogs.general.userinfo": {"name": "User Info", "description": "User, role, and emoji lookup tools."},
    "cogs.general.snipe": {"name": "Snipe", "description": "Deleted and edited message recall."},
    "cogs.general.help": {"name": "Help", "description": "Branded help and command discovery UI."},
    "cogs.general.reminders": {"name": "Reminders", "description": "Scheduled reminders and reminder management."},
    "cogs.general.afk": {"name": "AFK", "description": "AFK status tracking and mention notices."},
    "cogs.moderation.kick": {"name": "Kick", "description": "Kick moderation actions."},
    "cogs.moderation.ban": {"name": "Ban", "description": "Ban and unban moderation actions."},
    "cogs.moderation.warn": {"name": "Warn", "description": "Warnings and warning history."},
    "cogs.moderation.clear": {"name": "Clear", "description": "Bulk message cleanup tools."},
    "cogs.moderation.mute": {"name": "Mute", "description": "Mute role management and muting actions."},
    "cogs.moderation.slowmode": {"name": "Slowmode", "description": "Channel rate-limit controls."},
    "cogs.moderation.timeout": {"name": "Timeout", "description": "Discord timeout actions."},
    "cogs.moderation.notes": {"name": "Notes", "description": "Moderator notes on members."},
    "cogs.moderation.thresholds": {"name": "Thresholds", "description": "Automatic escalation thresholds for warnings."},
    "cogs.roles.panels": {"name": "Role Panels", "description": "Self-assignable role panels."},
    "cogs.settings.config": {"name": "Config", "description": "Guild configuration and welcome settings."},
    "cogs.settings.aliases": {"name": "Aliases", "description": "Chat shortcuts that trigger slash commands."},
    "cogs.automod": {"name": "AutoMod", "description": "Spam, link, caps, mention, and word filters."},
    "cogs.logging.logger": {"name": "Logging", "description": "Audit and event logging pipeline."},
    "cogs.temprooms.rooms": {"name": "Temp Rooms", "description": "Temporary voice room lifecycle management."},
    "cogs.temprooms.invite": {"name": "Temp Invites", "description": "Invite flows for temporary voice rooms."},
    "cogs.community.custom_commands": {"name": "Custom Commands", "description": "Guild-defined custom command triggers."},
    "cogs.community.autoroles": {"name": "Autoroles", "description": "Automatic role assignment on join."},
    "cogs.community.polls": {"name": "Polls", "description": "Poll creation and poll lifecycle commands."},
    "cogs.community.starboard": {"name": "Starboard", "description": "Highlighted message curation."},
    "cogs.focus.timer": {"name": "Focus Timer", "description": "Focus sessions, timers, and session images."},
    "cogs.focus.profile": {"name": "Focus Profile", "description": "Focus stats and profile views."},
    "cogs.focus.pets": {"name": "Focus Pets", "description": "Companion and pet progression for focus."},
    "cogs.music.player": {"name": "Music Player", "description": "Voice playback engine and queue commands."},
    "cogs.music.lyrics": {"name": "Lyrics", "description": "Lyrics lookup tools."},
    "cogs.security.security": {"name": "Security", "description": "Verification and server lockdown controls."},
    "cogs.owner": {"name": "Owner", "description": "Owner-only administration commands."},
    "cogs.ipc_bridge": {"name": "IPC Bridge", "description": "Dashboard bridge for live operations."},
}

LOCKED_EXTENSIONS = {
    "cogs.owner",
    "cogs.ipc_bridge",
}


def extension_key(extension: str) -> str:
    return extension.removeprefix("cogs.").replace(".", "_")


def extension_meta(extension: str) -> dict:
    default_name = extension.split(".")[-1].replace("_", " ").title()
    meta = MODULE_METADATA.get(extension, {})
    return {
        "key": extension_key(extension),
        "ext": extension,
        "name": meta.get("name", default_name),
        "description": meta.get("description", "Runtime-managed Severus feature module."),
        "manageable": extension not in LOCKED_EXTENSIONS,
    }


def module_catalog(extensions) -> dict:
    return {extension_key(ext): extension_meta(ext) for ext in extensions}
